---
title: "GDP function"      
author: "A. Mathot"        
output: 
  flexdashboard::flex_dashboard: 
    theme: spacelab
runtime: shiny               
--- 

  
```{r packages, include=FALSE}
require(ggplot2)
require(plotly)  #Permet de voir les coordonnées du point où on pose son slider
require(shiny)
require(kableExtra)   #permet de faire des tables sympas
require(knitr)
require(readxl)
theme_set(theme_bw())
library(dplyr)           
library(tidyr)
library(pandocfilters)
library(tibble)  #Pour ajouter une colonne à un dataset
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(            #Chunk pour les options globales
  tidy    = "styler",
  comment = NA, # enlever les deux ## avant chaque ligne de résultats
  echo = FALSE  #Pas montrer le code
)
```


```{r}
data <- read.csv(file = "Data.csv", header = TRUE, sep = "\t",dec =",",row.names =1)   #charger le fichier csv
#Attention, bien choisir les arguments "header", "sep", "dec" et "row.names"
#Header = True : on a des "colnames"
#"\t": format tabset
# dec c'est le séparateur décimale
# row.names = 1 c'est pour avoir des noms de ligne = à la première colonne du dataset
```

# Structure of Data:
## {.sidebar} 

<br>

---

```{r}
sliderInput("range",                #On permet à l'utilisateur de choisir l'interval de lignes à afficher
    label = "Rows to display",  
    value = 25,                      #Valeur par défaut de la variable choisie
    min = 1, max = nrow(data),       #la valeur max est le nombre de ligne du data set, logique
    step = 1)                        #On définit le "pas" entre les valeurs possibles

```
---

##

###

<br>

```{r}
dataf <- data %>%                                   #rajouter une colonne en position 1
  add_column(Countries = c(row.names(data)),        #par un vecteur avec noms de lignes donc des pays
             .before = "X1960")        #cette fonction nécessite "Tibble", X1960 c'est l'ancienne 1 colonne de data       
renderTable({                                       #dataf est uniquement créé pour l'utilisation de la fun 
  rg <- input$range                                 #IMPORTANT: permet de rendre réactif, il faut d'abord stocker dans rg avant sinon avec range ça va pas
  rmarkdown::paged_table(dataf[1:rg, ])             #ça fonctionne pas avec data d'où dataf
  #rg sera le numéro de la ligne finale à display
    })
#Rendertable c'est pour le contexte réactiffff
```




# Static graph:
## {.sidebar}

<br>

---

```{r}
Nbr = c(1:267)    #création d'un vecteur pour faire un data frame de simplement 2 colonnes
Pays = c(row.names(data)) #vecteur contennat les noms des lignes du jeux de donnée "data"
Data <- data.frame(x = Nbr, y = Pays)  #création du dataframe
Data |>         #on va faire un tableau mais cela nécessite de charger "knitr" pour la fct kable
  knitr::kable(
    caption = "Number to choose for the value of a for the chosen Country", col.names = c("a", "Country"))  #les label de ce tableau

```

```{r}
rmarkdown::paged_table(Data)           #On va display le tableau grâce à la fonction paged_table
```

---

##

###



```{r}
y <- data[18,]                                 #on sélectionne la ligne 18 ainsi que toutes les colonnes
x <- as.numeric(data[267,1:62])                #on sélectionne DE data la ligne 267 ainsi que les colonnes de 1 à 62, transformer en numérique, c'est IMPORTANT
Y <- as.numeric(y[1, 1:62])                   #on sélectionne de y la ligne 1 ainsi que les colonnes de 1 à 62, transformer en numérique, c'est IMPORTANT
Data = data.frame(x, Y)                        #On en fait un data frame pour pouvoir faire le graphe en ggplot
Country1 <- ggplot(Data, aes(x = x, y = Y)) +  #On cré un objet "Country1" qui est un plot 
  geom_line(color = "red")+
  geom_point(color = "black", shape = 8)+
  labs(title = "Gdp of Belgium (18) over years", x = "Years", y = "Gdp")
ggplotly(Country1)                            #Permet de voir les coordonnées du point où on pose son slider
```

# Display the chosen country:
## {.sidebar}

<br>

---
```{r}
Nombre = c(1:267)                              #Même chose que au dessus mais avec des ID différents
Pays = c(row.names(data))
Data1 <- data.frame(x = Nombre, y = Pays)
```

```{r}                                         
selectInput(                                   #On permet à l'utilisateur de chosir parmi les noms des pays
    inputId = "pays",               
    label = "Choose a country",                #titre
    choice = row.names(data),                  #On permet à l'utilisateur de chosir parmi les noms des pays
    selected = "Belgique"                      #Par défaut, c'est ça qui est présélectionné
  )
```

---

##

###

```{r}
renderPlot({                                   #le RENDER est important pour la réactivité
    pAys <- input$pays                         #on utilise l'ID de l'objet réactif pour créer une nouvelle variable qui sera updated à chaque choix de l'user
    Frame <- data.frame(x = c(as.numeric(data[267,1:62])), y = c(as.numeric(data[pAys, 1:62])))        #Data frame pour le ggplot avec la variable réactive
    ggplot(data = Frame, aes(x = x, y = y)) +                    
      geom_point(color = "black", shape = 8)+
      geom_line(color = "red")+
      labs(title = paste('Evolution of the gdp of',pAys, '.'), y = "GDP",x = "Years")    #titre ser automatiquement updated en fct du choix de l'user
})
```
